### ISSUE TITLE
Create form with mixed model fields

### ISSUE THREAD

**Issue by Rojo** [nRike/devf#16]
The [`Participants#new`](https://github.com/nRike/devf/blob/feature-integration-with-conekta/app/views/participants/new.html.erb#L50) view requires to get a list of the available programs from the `Program` model, fill a dropdown input from it, and set a hidden field with the `program.id` of the selected program.

Or, being dirty, it can be harcoded in the HTML for now.

**Comment by nRike** [comment]
I'm getting this error:

Association cannot be used in forms not associated with an object

 when trying to use <%=f.association :program %> inside the participants/new form.

Also tried `has_many :programs, trough: payments` in the Program model but still not working though.

**Comment by nRike** [comment]
Solved in #16
