### ISSUE TITLE
Functionality and variable tests to Signup Form

### ISSUE THREAD

**Issue by nRike** [nRike/devf#29]
The `participants/new`form seems pretty solid right now but during the demo today failed couple of times, mostly because the program selection and other variables receiving null in the PaymentsController. 

We need to find the tool/technique to test the form and inspect their parameters, and if so, display correctly the errors.

**Comment by Rojo** [comment]
Please check if https://github.com/nRike/devf/pull/42 improved this situation.

**Comment by nRike** [comment]
Yes, I reviewed #42 and all works great!
