### ISSUE TITLE
Functionality and variable tests to Payment Form

### ISSUE THREAD

**Issue by nRike** [nRike/devf#30]
The `payments/new`form seems pretty solid right now but during the demo today failed couple of times, mostly because the program selection and other variables receiving null in the PaymentsController. 

We need to find the tool/technique to test the form and inspect their parameters, and if so, display correctly the errors.

Also this form needs a general clean up of the fields, and if makes sense, `change form_for` method for `simple_form_for` provided by `simple form` gem.

**Comment by Rojo** [comment]
Please, check if https://github.com/nRike/devf/pull/42 improves this situation.

**Comment by nRike** [comment]
Yes, gonna try them tomorrow I guess @Rojo, Conekta is down right now :rabbit:

**Comment by nRike** [comment]
Yes! #42 closed the thing!
